# Generated by Django 5.1.2 on 2025-03-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payme", "0002_paymetransactions_fiscal_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymetransactions",
            name="fiscal_data",
            field=models.JSONField(default=dict),
        ),
    ]
