# Generated by Django 5.2 on 2025-04-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0003_alter_paymetransactions_fiscal_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymetransactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
